### ISSUE TITLE
go get github.com/glycerine/sshego fail

### ISSUE THREAD

**Issue by orange-jacky** [glycerine/sshego#3]
go1.12   use gomodule method

macbookpro:Downloads fredlee$ go get github.com/glycerine/sshego
go: finding github.com/mailgun/log latest
go: finding github.com/glycerine/greenpack/msgp latest
go: finding github.com/pquerna/otp/totp latest
go: finding github.com/glycerine/go-unsnap-stream latest
go: finding github.com/skratchdot/open-golang/open latest
go: finding github.com/skratchdot/open-golang latest
go: finding golang.org/x/crypto/ed25519 latest
go: finding golang.org/x/crypto/curve25519 latest
go: finding golang.org/x/crypto latest
go: finding github.com/boombuler/barcode/qr latest
# github.com/glycerine/sshego
../Documents/develop/go/workspace/pkg/mod/github.com/glycerine/sshego@v7.0.3+incompatible/mailgun.go:131:26: too many arguments in call to mailgun.NewMailgun
	have (string, string, string)
	want (string, string)

**Comment by orange-jacky** [comment]
why close it

**Comment by glycerine** [comment]
because it was fixed

**Comment by orange-jacky** [comment]
i use go module methto to download it 
it still exist

go get github.com/glycerine/sshego
# github.com/glycerine/sshego
../Documents/develop/go/workspace/pkg/mod/github.com/glycerine/sshego@v7.0.3+incompatible/mailgun.go:131:26: too many arguments in call to mailgun.NewMailgun
	have (string, string, string)
	want (string, string)

**Comment by glycerine** [comment]
you've locked the sshego version at the old broken state and you wonder why it stays broken?

C'mon.

**Comment by orange-jacky** [comment]
i use go1.12, you can have a try, it do fail
i need this package support go1.12, could you reprocude the issue and fix it

macbookpro:workspace fredlee$ go get github.com/glycerine/sshego
go: finding github.com/pquerna/otp/totp latest
go: finding github.com/glycerine/greenpack/msgp latest
go: finding github.com/mailgun/log latest
go: finding github.com/glycerine/go-unsnap-stream latest
go: finding github.com/skratchdot/open-golang/open latest
go: finding github.com/skratchdot/open-golang latest
go: finding golang.org/x/crypto/curve25519 latest
go: finding golang.org/x/crypto/ed25519 latest
go: finding golang.org/x/crypto latest
go: finding github.com/boombuler/barcode/qr latest
# github.com/glycerine/sshego
pkg/mod/github.com/glycerine/sshego@v7.0.3+incompatible/mailgun.go:131:26: too many arguments in call to mailgun.NewMailgun
	have (string, string, string)
	want (string, string)
macbookpro:workspace fredlee$

**Comment by orange-jacky** [comment]
i use go1.12 gomodule method, it need you write version of the mailgun.go
could you update your code support go mod ?
